java:
  image: 'https://hmctspublic.azurecr.io/sscs/bulk-scan:latest'
  applicationPort: 8090
  keyVaults:
    sscs-bulk-scan:
      resourceGroup: sscs-bulk-scan
      secrets:
        - sscs-s2s-secret
        - idam-sscs-systemupdate-user
        - idam-sscs-systemupdate-password
        - idam-sscs-oauth2-client-secret
  environment:
    REFORM_TEAM: sscs
    REFORM_SERVICE_NAME: bulk-scan
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
    IDAM_OAUTH2_REDIRECT_URL: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
    IDAM_URL: "https://idam-api.aat.platform.hmcts.net"
    IDAM_OAUTH2_CLIENT_ID: "sscs"
    IDAM_S2S_AUTH_MICROSERVICE: "sscs_bulkscan"
    LOGBACK_REQUIRE_ALERT_LEVEL: "false"
    LOGBACK_REQUIRE_ERROR_CODE: "false"
    WEBSITE_LOCAL_CACHE_OPTION: "Always"
    WEBSITE_LOCAL_CACHE_SIZEINMB: "300"
    WEBSITE_NODE_DEFAULT_VERSION: "8.11.1"
    WEBSITE_SLOT_POLL_WORKER_FOR_CHANGE_NOTIFICATION: "0"
    NODE_PATH: "D:\\home\\site\\wwwroot"
    IDAM_S2S_AUTH: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
    CORE_CASE_DATA_API_URL: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
    DOCUMENT_MANAGEMENT_URL: "http://dm-store-aat.service.core-compute-aat.internal"
