server:
  port: 8090

management:
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: SscsBulkScan

ccd:
 case:
  jurisdiction: SSCS
  type: Benefit
  eventId: appealCreated

core_case_data:
  api:
    url: http://localhost:4452


display.case.error: true
display.case.warning: false

idam:
  s2s-auth:
    url: http://localhost:4502

allowed-services-for-callback : ccd_data  # comma separated list of service names
