server:
  port: 8090

management:
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: SscsBulkScan

ccd:
 case:
  jurisdictionId: ${CCD_CASE_JURISDICTION_ID:SSCS}
  type: ${CCD_CASE_TYPE:Benefit}
  eventId: ${CCD_CASE_EVENT_ID:appealCreated}


