server:
  port: 8090

management:
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: SscsBulkScan
  devtools:
    restart:
      enabled: true

core_case_data:
  api:
    url: http://localhost:4452

display:
  case :
    error : false
    warning: false
