idam:
 s2s-auth:
  url: false

ccd:
 case:
  jurisdiction: SSCS
  type: Benefit
  eventId: appealCreated

core_case_data:
 api:
  url: http://localhost:4000

allowed-services-for-callback : test_service
